/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.entornos;


import jakarta.persistence.EntityManager;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Medac
 */
public class CVempresa extends javax.swing.JFrame {

    /**
     * Creates new form CVcliente
     */
    public CVempresa() {
        initComponents();
    }
    
    public CVempresa(EntityManager manager, Cempresa empresa) {
    
        initComponents();
        
        this.empresa = empresa;
        
        this.manager = manager;
               
        this.modificando = false;
        
        // Relleno todos campos para mostrarlos en pantalla
        this.cargaValores();
        
        // bloqueo campos para evitar cambios accidentales
        this.bloqueaCampos(modificando);
        
        //pongo los textos por defecto en los botones
        this.cambiaTextoBotones(modificando);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuerpo = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbNif = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        tfNif = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        panelPie = new javax.swing.JPanel();
        btBorrar = new javax.swing.JButton();
        btGuadar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        panelCabecera = new javax.swing.JPanel();
        lbTItulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos Empresa");

        lbNombre.setText("Nombre");

        lbNif.setText("DNI / NIF");

        lbDireccion.setText("Dirección");

        tfNif.setText("jTextField1");
        tfNif.setToolTipText("Identificación fiscal");
        tfNif.setNextFocusableComponent(tfNombre);
        tfNif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNifFocusLost(evt);
            }
        });

        tfNombre.setText("jTextField1");
        tfNombre.setToolTipText("Nombre de la empresa");
        tfNombre.setNextFocusableComponent(tfDireccion);
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });

        tfDireccion.setText("jTextField1");
        tfDireccion.setToolTipText("Dirección de la empresa");
        tfDireccion.setNextFocusableComponent(btGuadar);
        tfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDireccionFocusLost(evt);
            }
        });

        jLabel1.setText("Mail");

        tfCorreo.setText("jTextField1");
        tfCorreo.setToolTipText("Correo electrónico");
        tfCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCorreoFocusLost(evt);
            }
        });

        lbTelefono.setText("Teléfono");

        tfTelefono.setText("jTextField1");
        tfTelefono.setToolTipText("Teléfono");

        javax.swing.GroupLayout panelCuerpoLayout = new javax.swing.GroupLayout(panelCuerpo);
        panelCuerpo.setLayout(panelCuerpoLayout);
        panelCuerpoLayout.setHorizontalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNif)
                    .addComponent(lbNombre)
                    .addComponent(lbDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDireccion)
                    .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCuerpoLayout.createSequentialGroup()
                        .addComponent(tfNif, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lbTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addComponent(tfCorreo)))
        );
        panelCuerpoLayout.setVerticalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNif)
                    .addComponent(tfNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(panelCuerpo, java.awt.BorderLayout.LINE_START);

        btBorrar.setForeground(new java.awt.Color(204, 0, 0));
        btBorrar.setText("Borrar");
        btBorrar.setToolTipText("Borra cliente actual");
        btBorrar.setName(""); // NOI18N
        btBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBorrarMouseClicked(evt);
            }
        });
        panelPie.add(btBorrar);

        btGuadar.setText("Modficar");
        btGuadar.setNextFocusableComponent(btCancelar);
        btGuadar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGuadarMouseClicked(evt);
            }
        });
        btGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuadarActionPerformed(evt);
            }
        });
        panelPie.add(btGuadar);

        btCancelar.setText("Salir");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelarMouseClicked(evt);
            }
        });
        panelPie.add(btCancelar);

        getContentPane().add(panelPie, java.awt.BorderLayout.SOUTH);

        lbTItulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lbTItulo.setText("Datos Empresa");
        lbTItulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 18))); // NOI18N
        panelCabecera.add(lbTItulo);

        getContentPane().add(panelCabecera, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuadarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGuadarMouseClicked
        // Activo la maraca que me permite saber si estoy modificando
        this.modificando=true;
        
        //  desbloqueo los campos del formulario
        this.bloqueaCampos(modificando);

    }//GEN-LAST:event_btGuadarMouseClicked

    private void btCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseClicked

        if (this.modificando)
        {
            this.modificando=!this.modificando;
            cargaValores();
            this.bloqueaCampos(modificando);
            this.cambiaTextoBotones(modificando);
            
        }else
            this.dispose();

    }//GEN-LAST:event_btCancelarMouseClicked

    private void tfNifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNifFocusGained
        
        if (CVempresa.SIN_NIF.equals(tfNif.getText()))
        {
            tfNif.setText("");
        }
        
    }//GEN-LAST:event_tfNifFocusGained

    private void tfNifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNifFocusLost
        
        if (tfNif.getText().isEmpty())
        {
            tfNif.setText(CVempresa.SIN_NIF);
        }
        
    }//GEN-LAST:event_tfNifFocusLost

    private void btGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuadarActionPerformed
        
        if(this.modificando)
        {
            if( this.compruebaCampo(this.tfNif,CVempresa.SIN_NIF) &&
                this.compruebaCampo(this.tfDireccion,CVempresa.SIN_DIRECCION)&&
                this.compruebaCampo(this.tfNombre,CVempresa.SIN_NOMBRE)&& 
                this.compruebaCampo(tfCorreo, CVempresa.SIN_CORREO)&&
                this.validarTelefono(this.tfTelefono))           
            {
                
                    if (this.grabaRegistro())
                    {
                        this.modificando=false;
                        this.cambiaTextoBotones(modificando);
                        this.bloqueaCampos(modificando);
                        JOptionPane.showMessageDialog(this,this.TEXTO_GUARDADO + !modificando, TITULO_MENSAJE, JOptionPane.INFORMATION_MESSAGE);
                        
                    }else
                    {
                        JOptionPane.showMessageDialog(this,this.TEXTO_GUARDADO + !modificando, TITULO_MENSAJE, JOptionPane.WARNING_MESSAGE);
                    }
            }
                   
            
        }else
        {
            this.modificando = true;
            this.cambiaTextoBotones(modificando);
            this.bloqueaCampos(modificando);
        }
            
    }//GEN-LAST:event_btGuadarActionPerformed

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        if (CVempresa.SIN_NOMBRE.equals(tfNombre.getText()))
        {
            tfNombre.setText("");
        }
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
        if (tfNombre.getText().isEmpty())
        {
            tfNombre.setText(CVempresa.SIN_NOMBRE);
        }
        
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusGained
        if (CVempresa.SIN_DIRECCION.equals(tfDireccion.getText()))
        {
            tfDireccion.setText("");
        }
    }//GEN-LAST:event_tfDireccionFocusGained

    private void tfDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusLost
        if (tfDireccion.getText().isEmpty())
        {
            tfDireccion.setText(CVempresa.SIN_DIRECCION);
        }
    }//GEN-LAST:event_tfDireccionFocusLost

    private void btBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBorrarMouseClicked
        
        
        
        JOptionPane.showMessageDialog(this,"NO se puede borrar la empresa", TITULO_MENSAJE, JOptionPane.INFORMATION_MESSAGE);
           
        
       
    }//GEN-LAST:event_btBorrarMouseClicked

    private void tfCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCorreoFocusGained
        if (CVempresa.SIN_CORREO.equals(tfCorreo.getText()))
        {
            tfCorreo.setText("");
        }
    }//GEN-LAST:event_tfCorreoFocusGained

    
    private void tfCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCorreoFocusLost
        if (tfCorreo.getText().isEmpty())
        {
            tfCorreo.setText(CVempresa.SIN_CORREO);
        }
    }//GEN-LAST:event_tfCorreoFocusLost

    private boolean validarTelefono(JTextField campo)
    {
        String text = campo.getText();
        
        //return (text.length()==9);
        return true; 
        //Pattern pattern = Pattern.compile("[0-9]{9}");
        //Matcher matcher = pattern.matcher(text);
        //return matcher.matches();
    }
    
    private boolean validarCorreo(JTextField campo)
    {
        String text = campo.getText();
        Pattern pattern = Pattern.compile("[a-z][0-9]@[a-z].[a-z]");
        Matcher matcher = pattern.matcher(text);
        return matcher.matches();
    }
    
    
    /**
     * Funcion para comprobar que los valores no son los establecidos en el formulario
     * @param campo campo del formulario a comprobar
     * @param cadena texto por defecto de la clase
     * @return devuleve falso si los campos coinciden
     */
    private boolean compruebaCampo(JTextField campo, String cadena)
    {
        boolean resultado =false;
      
        if (cadena.equals(campo.getText()) || campo.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this,this.TEXTO_REVISAR + campo.getToolTipText(), TITULO_MENSAJE, JOptionPane.ERROR_MESSAGE);
            campo.setForeground(Color.red);
        }else{
            
            campo.setForeground(Color.black);
            resultado=true;
        }
                
        return resultado; 
    }
    
    /**
     * Funcion para grabar registro
     */
    private boolean grabaRegistro()
    {
        
        this.empresa.setIdFiscal(this.tfNif.getText());
        this.empresa.setNombre(this.tfNombre.getText());
        this.empresa.setDireccion(this.tfDireccion.getText());
        this.empresa.setTelefono(Integer.valueOf(this.tfTelefono.getText()));
        this.empresa.setMail(this.tfCorreo.getText());
        
        this.manager.getTransaction().begin();
        
        manager.merge(this.empresa);
        
        this.manager.getTransaction().begin();
        
       return true;

    }
    
     private void cambiaTextoBotones(boolean modificando)
    {
        
        if (this.modificando)
        {
            this.btCancelar.setText(CANCELAR);
            this.btGuadar.setText(GUARDAR);
            
        }else{
            
            this.btCancelar.setText(SALIR);
            this.btGuadar.setText(MODIFICAR);
            
        }
        
    }
    
    /**
     * Funcion que activa o desactiva la edicion del formulario
     * @param sn parametro que activa o desactiva la edicion del formulario
     */
    private void bloqueaCampos(boolean sn)
    {
        this.tfDireccion.setEditable(sn);
        this.tfNombre.setEditable(sn);
        this.tfNif.setEnabled(sn);
        this.tfCorreo.setEnabled(sn);
        this.tfTelefono.setEnabled(sn);       
        
    }
    
    /**
     * Funcion para cargar los valores de un sujeto
     */
    private void cargaValores()
    {
        
        this.tfDireccion.setText(this.empresa.getDireccion());
        this.tfNif.setText(this.empresa.getIdFiscal());
        this.tfNombre.setText(this.empresa.getNombre());
        this.tfCorreo.setText(this.empresa.getMail());
        this.tfTelefono.setText(String.valueOf(this.empresa.getTelefono()));
        
    }
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CVempresa().setVisible(true);
            }
        });
    }
    
    Cempresa empresa;
    
    private EntityManager manager;
           
    final static String GUARDAR="Guardar";
    final static String MODIFICAR="Modificar";
    
    final static String SALIR="Salir";
    final static String CANCELAR="Cancelar";
    
    final static String TITULO_MENSAJE="Datos Formulario";
    
    static final String SIN_NOMBRE="Nombre Empresa S.L.";
    static final String SIN_DIRECCION="Direccion de la empresa";
    static final String SIN_NIF="A000000";
    static final int SIN_TELEFONO=999999999;
    static final String SIN_CORREO="DIRECCION@CORREO.ES";
    
    static final String NOMBRE_TABLA = "EMPRESA";
    
    
    //variable para saber si estoy modificando
    boolean modificando;
   
    final String TEXTO_REVISAR="Revise ";
    final String TEXTO_GUARDADO="Registro guardado";
    
    final String TEXTO_BORRAR="¿Está Usted seguro de que desea borrar este registro?";
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuadar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNif;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTItulo;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelPie;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNif;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
